- client/package-lock.json
- client/src/App.js
- client/src/components/BillingView.js
- client/src/components/LandingPageView/Carousel.js
- client/src/components/LandingPageView/LandingPage.js
- client/src/components/ProgressView/ProgressList/ProgressList.js
- client/src/components/ProgressView/ProgressList/ProgressListItem.js
- client/src/components/ProgressView/ProgressTracker.js
- client/src/components/ProgressView/ProgressView.js
- client/src/components/ProgressView/SubmitProgress.js
- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/ScheduleView.js
- client/src/components/ScheduleView/ScheduleWorkout/ListItem.js
- client/src/components/ScheduleView/ScheduleWorkout/ScheduleWorkoutList.js
- client/src/components/ScheduleView/WorkoutDetails.js
- client/src/components/SettingsView.js
- client/src/components/SideNav.js
- client/src/components/WorkoutsView/EditWorkout.js
- client/src/components/WorkoutsView/WorkoutCategory.js
- client/src/components/WorkoutsView/WorkoutCatergoryList.js
- client/src/components/WorkoutsView/WorkoutTitleList.js
- client/src/components/WorkoutsView/WorkoutsView.js
Description:
Set up basic file structure for all components and naming for folders. Began discussion on naming conventions for filenames, and will revisit individual filenames as needed.
Type of change:
File-Structure
How Has This Been Tested?
All files show no errors. App renders to the browser.
Checklist:
[x]  My code follows the style guidelines of this project
[x]  I have performed a self-review of my own code
[x]  My code has been reviewed by at least one peer
[x]  I have commented my code, particularly in hard-to-understand areas
[x]  I have made corresponding changes to the documentation
[x] My changes generate no new warnings
[x] I have added tests that prove my fix is effective or that my feature works
[x]  New and existing unit tests pass locally with my changes
[x] There are no …
> Frontend setup

- procfile
- server/.gitignore
- server/index.js
- server/knexfile.js
- server/package.json
- server/routes/usersRoute.js
Configured the knexfile to support Postgress server, added server and start script to the server package.json file. Created a heroku proc file to support deployment on heroku
> Backend deployment

- README.md
- client/src/App.js
- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.css
- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/ScheduleView.js
- client/src/components/ScheduleView/ScheduleWorkout/ListItem.js
- client/src/components/ScheduleView/ScheduleWorkout/ScheduleWorkoutList.js
- client/src/components/ScheduleView/WorkoutDetails.js
Passed needed props to schedule view and its child components. refactored needed components to function components to remove state. adjusted size and shape of calendar to allow for additional edits. Added data structure to README.md. Continued working on Schedule view page. Commented areas that will need further discussion/clarification.
Documentation. Front-end structure. Data management. Design.
All information renders correctly to the browser
> Solo commit -WD

- client/.gitignore
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Login.js
- client/src/components/Register.js
- client/src/mockData.js
> Firebase login

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/Login.js
- client/src/components/Register.js
- client/src/mockData.js
Setup firebase store and made functioning Register component to create users
> Setup firebase project, fucntioning register component

- server/routes/scheduleWorkoutsRoute.js
- server/routes/workoutsRoute.js
Co-authored-by: Chris Cedeno <chrisrey95@gmail.com>
> Completed endpoint for creating a new workout. Also GET scheduled workout

- server/api/server.spec.js
- server/package-lock.json
- server/routes/workoutsRoute.js
Continued working on POST and PUT endpoints for workouts route.
backend endpoints
Tested using postman. All endpoints work
> Continued working on endpoints for workouts route.

- client/src/App.js
- client/src/components/Login.js
- client/src/components/Register.js
- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/ScheduleView.js
- client/src/components/ScheduleView/ScheduleWorkout/ListItem.js
- client/src/components/ScheduleView/ScheduleWorkout/ScheduleWorkoutList.js
- client/src/components/ScheduleView/WorkoutDetails.js
- client/src/components/WorkoutsView/WorkoutCategory.js
- server/config/configureRoutes.js
- server/database/migrations/20190108153627_users.js
- server/index.js
- server/routes/authRoute.js
Added useEffect and useReducer to our application to initialize our firebase app.
> Added useEffect and useReducer to our application

- client/package-lock.json
- client/package.json
- client/src/components/SettingsView/BillingView.js
- client/src/components/SettingsView/SettingsView.js
- node_modules/react-stripe-checkout/.codeclimate.yml
- node_modules/react-stripe-checkout/.npmignore
- node_modules/react-stripe-checkout/.test-setup.js
- node_modules/react-stripe-checkout/.travis.yml
- node_modules/react-stripe-checkout/LICENSE.md
- node_modules/react-stripe-checkout/README.md
- node_modules/react-stripe-checkout/StripeCheckout.js
- node_modules/react-stripe-checkout/dist/main.js
- node_modules/react-stripe-checkout/index.d.ts
- node_modules/react-stripe-checkout/package.json
- node_modules/react-stripe-checkout/spec.js
- package-lock.json
- package.json
- server/config/configureRoutes.js
- server/database/migrations/20190108153627_users.js
- server/package-lock.json
- server/package.json
- server/routes/stripeRoutes.js
Implemented stripe into front end and back end. 
> Stripe final

- server/README.md
- server/__tests__/routes/usersRoute.spec.js
- server/routes/categoryRoute.js
- server/routes/metricRoute.js
- server/routes/usersRoute.js
- server/routes/workoutsRoute.js
Updated users route from getting user id from params.id to req.id
Added test's for users route
Updated README.md on server folder
> User Router tests, updated server README.md

- client/src/components/ScheduleView/Calendar.js
Completed functionality to render scheduled workout on it's particular date. Completed functionality to render specific component based on whether date has a workout already scheduled. -wd
Renders successfully to the browser. ReactDevtools all show correct data upon events
> Calendar Functionality

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/ProgressView/ProgressView.js
- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/ScheduleView.js
- client/src/components/ScheduleView/WorkoutDetails.js
changed incoming URL to backend server
renders correctly to the browser
> changed incoming URL to back-end server instead of dummydata.

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/SettingsView/BillingView.js
- client/src/components/SettingsView/SettingsView.js
- server/package-lock.json
Created conditional render for premium member on settings page and style
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
Through dev tools. div renders when premium is met. 
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] …
> Premium member

- client/src/components/LandingPageView/LandingPage.js
- client/src/components/WorkoutsView/EditWorkout.js
- client/src/components/WorkoutsView/WorkoutsView.js
- package-lock.json
Minor styling changes for clarity, and adds Dropdown menu components so we can start working on them.
Have not tested anything yet, need to get the dropdown menus built out a little more.
> Workout view

- client/src/App.js
- client/src/components/Navigation.js
- client/src/components/ProgressView/ProgressView.js
- client/src/components/ScheduleView/ScheduleView.js
- client/src/components/SettingsView/SettingsView.js
- client/src/components/WorkoutsView/WorkoutsView.js
- client/src/requireAuth.js
Created authRequired HOC checks for token on protected routes
Created logout button on the header
> Created authRequired HOC and Logout button

- client/package-lock.json
- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/ExerciseDetails.js
- client/src/components/ScheduleView/WorkoutDetails.js
Created new component, exercise details, that is being used to list particular exercises. Used hook to set the state of exercise status by check box
checkbox updates state. Renders to browser
> Calendar and WorkoutDetails Component

- client/package-lock.json
- client/src/components/SettingsView/BillingView.js
- client/src/components/SettingsView/SettingsView.js
- server/routes/stripeRoutes.js
Added conditional render for premium button and a little styling added
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my …
> Cancel premium

- client/src/components/SettingsView/SettingsView.js
> Fixed PUT method on settings to add data

- client/src/requireAuth.js
Fixed HOC compiling error originating from requireAuth component
> fixed error on requireAuth component

- client/src/components/WorkoutsView/WorkoutCategory.js
- client/src/components/WorkoutsView/WorkoutCategoryList.js
successfully rendered the workouts that are assigned to each category
Renders correctly to browser. Categories only render the workouts assigned to the category
> successfully rendered the workouts that are assigned to each category

- server/database/migrations/002_metrics.js
- server/database/seeds/002_metrics.js
- server/database/seeds/003_category.js
- server/database/seeds/004_workouts.js
- server/database/seeds/005_exercises.js
- server/database/seeds/006_schedule_workouts.js
- server/database/seeds/007_schedule_exercises.js
- server/routes/scheduleWorkoutsRoute.js
- server/routes/workoutsRoute.js
Fixed workout and schedule workout route only returning an object instead of an array
> Fix workout route and added additional seeds

- server/config/authenticate.js
- server/routes/usersRoute.js
Fixed user route to return proper user object
> Fix userRoute

- server/routes/workoutsRoute.js
Co-authored-by: Bill DiFulvio <w.difulvio523@gmail.com>
Initial set up of adding a new workout. Added the category id to the initial workout that is on state
Renders to browder, state updates correctly
> Added the category id to the initial workout that is on state

- client/src/App.js
- client/src/components/SettingsView/SettingsView.js
-Added functionality to settings to change password and email. 
Through firebase and front end as well as postman and insomnia
> Change email password

- client/package-lock.json
- client/package.json
- client/src/components/ProgressView/AddMetricModule.js
- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ProgressView/ProgressGraph.js
- client/src/components/ProgressView/ProgressHeader.js
- client/src/components/ProgressView/ProgressView.js
- server/database/seeds/001_users.js
- server/database/seeds/002_metrics.js
- server/database/seeds/003_category.js
- server/database/seeds/004_workouts.js
- server/database/seeds/005_exercises.js
- server/database/seeds/006_schedule_workouts.js
- server/database/seeds/007_schedule_exercises.js
- server/routes/scheduleWorkoutsRoute.js
- server/routes/usersRoute.js
- server/routes/workoutsRoute.js
Fixed Seeds for Postgres
Added date functionality for Adding a metric
> Fixed Seeds for Postgress, added date functionality for Adding a metric

- client/package-lock.json
- client/src/components/ProgressView/AddMetricModule.js
- client/src/components/ProgressView/ProgressView.js
Add metric component selecting date added with react-calendar
Error handling for same day selection added
> Add metric component

- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.js
Added functionality to create a scheduled workout and add it to the calendar
Scheduled workouts get correctly sent to database. Newly created workouts render correctly to the calendar.
> Add Schedule workout functionality.

- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/ExerciseDetails.js
- client/src/components/ScheduleView/WorkoutDetails.js
-Added functionality for exercise completed
- [x ] New feature (non-breaking change which adds functionality)
- [x ] This change requires a documentation update
- [x ] Complete, tested, ready to review and merge
-Testing state and seeing a change in state
- [x ] My code follows the style guidelines of this project
- [x ] I …
> Completed functionality for marking an exercise as complete.

- client/package-lock.json
- client/src/components/Navigation.js
- client/src/components/ProgressView/AddMetricModule.js
- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ProgressView/ProgressGraph.js
- client/src/components/ProgressView/ProgressHeader.js
- client/src/components/ProgressView/ProgressView.js
- client/src/index.js
Added delete metric functionality 
> Added delete metric functionality 

- client/src/components/WorkoutsView/Categories.js
- client/src/components/WorkoutsView/EditWorkout.js
- client/src/components/WorkoutsView/WorkoutList.js
- client/src/components/WorkoutsView/WorkoutsView.js
- client/src/index.js
Added a conditional render to remove the ability to add a workout and begin to edit the selected workout. 
Fixes # (issue) - Starts to implement the ability to edit a workout. 
Component renders to the screen correctly upon user input. 
> Edit workout

- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/ScheduleView.js
- client/src/components/ScheduleView/WorkoutDetails.js
- server/routes/scheduleWorkoutsRoute.js
Completed route for deleting a scheduled workout. Fixed calendar issue where it did not render when no scheduled workouts.
Need to update heroku with new endpoint
> Delete Scheduled Workout

- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/WorkoutDetails.js
- client/src/index.js
- server/routes/scheduleWorkoutsRoute.js
Created ability to delete scheduled workout from the schedule view as well as fixing bug in backend endpoint. 
> completed functionality for unscheduling a workout.

- client/src/components/ScheduleView/AddWorkout.js
Fixed bug in add workout feature that didn't allow recurring workouts when less than seven days were left in the month.
All data successfully renders to the browser.
> Reoccurring scheduled workouts functionality

- client/src/components/ScheduleView/HooksCalendar.js
- client/src/components/ScheduleView/ScheduleView.js
Refactored Calendar component to use hooks. All functionality still working.
all functionality still works after refactor
> Calendar refactor

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/ScheduleView/Calendar.css
- client/src/components/ScheduleView/ExerciseDetails.js
- client/src/components/ScheduleView/HooksCalendar.js
- client/src/components/ScheduleView/ScheduleView.js
- client/src/components/ScheduleView/WorkoutDetails.js
- client/src/index.js
Began design for Calendar Desktop and Mobile view. Refactored conditional render to have modal always render
Changes render to screen.
> Mobile calendar view

- client/src/components/SettingsView/BillingView.js
- client/src/components/SettingsView/SettingsView.js
State for settings updates immediately now
Tested with front-end
> Settings State Fixed

- client/src/StyleTheme.js
- client/src/components/SideNavigation.js
- client/src/components/WorkoutsView/Semantic/AddWorkouts.js
- client/src/components/WorkoutsView/Semantic/CategoryDropDown.js
- client/src/components/WorkoutsView/Semantic/MyWorkouts.js
- client/src/components/WorkoutsView/index.js
- client/src/index.js
- client/src/shared/DropDown.js
- client/src/shared/Input.js
- client/src/shared/Styles.js
Creates reusable Input component and refactors add workout to make use of it.
> Reusable Input Component

- client/src/App.js
- client/src/components/Login.js
- client/src/components/Register.js
- client/src/components/SettingsView/MainSettings.js
- client/src/components/SettingsView/Password.js
- client/src/components/SettingsView/SettingsView.js
- client/src/components/SettingsView/settings.css
- client/src/index.js
Changed settings into two components 
- [x ] Bug fix (non-breaking change which fixes an issue)
> Tab settings

- client/src/components/SettingsView/BillingView.js
- client/src/components/SettingsView/MainSettings.js
- client/src/components/SettingsView/Password.js
- client/src/components/SettingsView/SettingsView.js
Co-authored-by:William Difulvio <w.difulvio523@gmail.com>
> Finished Settings page and password change

- client/src/components/LandingPageView/LandingPage.js
Reuses Button component so that styling is consistent throughout the site.
Fixes # (issue) - buttons weren't consistent.
> Button Styling

- client/src/components/Navigation.js
- client/src/components/ProgressView/MetricModule/AddMetric.js
- client/src/components/ProgressView/MetricModule/EditMetric.js
- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ProgressView/ProgressGraph/Details.js
- client/src/components/ProgressView/ProgressGraph/Graph.js
- client/src/components/ProgressView/ProgressGraph/TabSelection.js
- client/src/components/ProgressView/ProgressGraph/index.js
- client/src/components/ProgressView/index.js
- client/src/components/SettingsView/BillingView.js
- client/src/components/SettingsView/MainSettings.js
- client/src/components/SettingsView/Password.js
- client/src/components/SettingsView/SettingsView.js
- client/src/components/WorkoutsView/WorkoutModule/AddWorkout.js
- client/src/shared/FormInput.js
- client/src/shared/FormModal.js
- server/database/seeds/006_schedule_workouts.js
- server/routes/scheduleWorkoutsRoute.js
Updated styling for Progress, Settings, Navbar to use consistent styling across the app
> Progress, Settings, Navbar Restyling

- client/src/components/WorkoutsView/CategoryDropDown.js
- client/src/components/WorkoutsView/WorkoutModule/AddWorkout.js
- client/src/index.js
- server/config/authenticate.js
- server/package-lock.json
- server/routes/workoutsRoute.js
User can add a category while creating a workout
User not able to add category after restyling
Category is added to the list after reload. 
Button renders to the screen correctly.
> Add category functionality

- client/package-lock.json
- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/HooksCalendar.js
Co-authored-by:Joseph Stanfield <jlstan06@hotmail.com>
Styling implementation and bug fixes for functionality
> implemented styling and fuctioning bugfixes for addworkout component.

- client/src/App.js
- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ProgressView/ProgressGraph/Details.js
- client/src/components/ProgressView/ProgressGraph/Graph.js
- client/src/components/ProgressView/ProgressGraph/index.js
- client/src/components/ProgressView/index.js
- server/config/authenticate.js
- server/database/seeds/004_workouts.js
Finished progress styling with mobile breakpoints
> Progress Styling and Mobile Breakpoints

- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/WorkoutsView/MyWorkouts.js
- client/src/components/WorkoutsView/WorkoutModule/AddWorkout.js
- client/src/components/WorkoutsView/WorkoutModule/EditWorkout.js
Brings in the Shared Button to the Add Workout page and Progress page.
Fixes # Button consistency
> Button fixes

- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.css
- client/src/components/ScheduleView/ExerciseDetails.js
- client/src/components/ScheduleView/HooksCalendar.js
- client/src/components/ScheduleView/WorkoutDetails.js
- client/src/shared/Input.js
- server/routes/scheduleWorkoutsRoute.js
Added upcoming workouts to calendar view. Updated Add Workout component to fit mobile view and desktop styling.
Output renders to browser.
> added upcoming workouts and styling

- client/src/components/Navigation.js
- client/src/components/ProgressView/ProgressGraph/Details.js
- server/routes/scheduleWorkoutsRoute.js
> Navigation Mobile Styling

- client/src/components/WorkoutsView/WorkoutModule/AddWorkout.js
- client/src/components/WorkoutsView/WorkoutModule/EditWorkout.js
Delete a workout, remove an exercise when making a workout & add a workout functionality complete. 
Functionality and user experience improvements in workouts page
user experience
- [] Complete, but not tested (may need new tests)
Data updates correctly on screen
Data updates in database
> pull from origin master

- client/src/components/WorkoutsView/MyWorkouts.js
- client/src/components/WorkoutsView/WorkoutModule/AddWorkout.js
Workouts page mobile responsive and button location fix. 
Fixes # (issue) - Workouts page not mobile responsive after styling update. 
Page appears correctly at mobile size on screen
Page renders correctly locally.
> Mobile styling for workouts page

- client/src/components/ScheduleView/HooksCalendar.js
Refactored displayworkouts styled component for consistency
> Refactored displayworkouts styled component

- client/src/components/ScheduleView/Calendar.css
- client/src/components/ScheduleView/HooksCalendar.js
design decisions on upcoming workouts
> design decisions on upcoming workouts

- client/package-lock.json
- client/package.json
- client/src/components/SettingsView/MainSettings.js
- client/src/components/SettingsView/Password.js
- client/src/components/SettingsView/SettingsView.js
> Styling for settings page finished

- client/src/components/ProgressView/ProgressGraph/Graph.js
- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.css
- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/WorkoutDetails.js
- client/src/components/ScheduleView/index.js
Styling Updates to Calendar View
> Styling Updates to Calendar View

- client/src/components/ProgressView/ProgressGraph/TabSelection.js
- client/src/components/SettingsView/MainSettings.js
- client/src/components/SettingsView/Password.js
- client/src/components/SettingsView/SettingsView.js
Styling for tabs in settings and progress
> Styling for progress and settings tab

- client/src/components/WorkoutsView/CategoryDropDown.js
- client/src/components/WorkoutsView/WorkoutModule/AddWorkout.js
- client/src/components/WorkoutsView/WorkoutModule/EditWorkout.js
- client/src/shared/Button.js
Edit workout mobile styling complete
Fixes # (issue) - mobile not looking good for edit workout. 
Edit a workout not looking correct on mobile view
Mobile styling
Page renders correctly on mobile view. 
Functionality works on mobile view.
> Workouts mobile style

- client/public/index.html
- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/ScheduleView/Calendar.css
- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/WeeklyWorkouts.js
- client/src/components/ScheduleView/WorkoutDetails.js
- client/src/index.js
> Fixed Calendar Bugs

- server/README.md
Updates the README on the server side to include recent changes made to endpoints.
> README update

- client/src/components/LandingPageView/LandingPage.js
- client/src/components/Loading.js
- client/src/components/Login.js
- client/src/components/Navigation.js
- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ProgressView/ProgressGraph/TabSelection.js
- client/src/components/Register.js
Navigation on login Render, Login/Register error handling
> Navigation on login Render, Login/Register error handling

- client/src/components/ScheduleView/AddWorkout.js
- client/src/components/SettingsView/BillingView.js
- client/src/components/SettingsView/Password.js
- client/src/components/SettingsView/SettingsView.js
Functionality for add workout complete. BugFix completed. Styling completed. Setting style completed.
> Schedule workout changes

- client/src/components/LandingPageView/LandingPage.js
Adds a Down Arrow 'hint' for scrolling through features on the landing page.
> Down Arrow

- client/src/components/LandingPageView/LandingPage.js
- client/src/components/Login.js
- client/src/components/Navigation.js
- client/src/components/ProgressView/index.js
- client/src/components/Register.js
- client/src/components/WorkoutsView/WorkoutModule/AddWorkout.js
- client/src/components/WorkoutsView/WorkoutModule/EditWorkout.js
- client/src/index.js
- server/routes/workoutsRoute.js
Edit Progress Server and Backed functionality
> Edit Progress Server and Backed functionality

- README.md
- client/README.md
- server/README.md
- server/routes/metricRoute.js
Created client readme and updated the server readme
> Updated Server Readme/Client Readme

- client/src/components/ScheduleView/WorkoutDetails.js
- client/src/components/WorkoutsView/MyWorkouts.js
- client/src/index.css
- client/src/index.js
A list exercises associated with a workout are now shown when you hit the down arrow. 
Exercises not showing on workouts page when a workout is selected. 
Feature completion.
Component renders correctly to the screen. 
Edit functionality works.
> Workout dropdown

- client/src/components/LandingPageView/LandingPage.js
- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ScheduleView/WeeklyWorkouts.js
- client/src/components/SettingsView/SettingsView.js
- client/src/shared/FormInputTwo.js
Landing page responsive design.  Phone no longer required to enter password when changing something on the settings page.  
> Some Responsive styling and Error Handling

- client/src/components/Login.js
- client/src/components/Register.js
> Recentered forms

- client/src/components/LandingPageView/LandingPage.js
- client/src/components/ProgressView/MetricModule/AddMetric.js
- client/src/components/ProgressView/MetricModule/EditMetric.js
- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ProgressView/ProgressGraph/Details.js
- client/src/components/ProgressView/ProgressGraph/Graph.js
- client/src/components/ProgressView/index.js
- client/src/index.js
- client/src/shared/Input.js
Premium features and styling bug fixes
> Premium features and styling bug fixes

- client/src/components/LandingPageView/LandingPage.js
responsive issues fixed and safari compatibility hopefully fixed
> responsive issues fixed and safari compatibility hopefully fixed

- client/src/components/Navigation.js
- client/src/components/ProgressView/MetricModule/AddMetric.js
- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ProgressView/ProgressGraph/Details.js
- client/src/components/ProgressView/index.js
- client/src/index.css
- client/src/shared/FormModal.js
> Progress View Style Updates

- client/package-lock.json
- client/src/components/WorkoutsView/MyWorkouts.js
Changed the location of the up/down arrows, changed the edit icon to an edit button with text, added a placeholder for when a user has no workouts & made the entire workout clickable to display the exercises. 
Changes made based on user feedback. 
Cosmetic based on user testing. 
Page & component displays correctly to the screen. 
Functionality remains after restyle.
> Up/Down Arrow Location Change, Edit Icon to Edit Button & No Workout Placeholder

- client/src/App.js
- client/src/components/LandingPageView/LandingPage.js
- client/src/components/Navigation.js
- client/src/components/SettingsView/BillingView.js
- client/src/components/SettingsView/MainSettings.js
- client/src/components/SettingsView/Password.js
- client/src/components/SettingsView/SettingsView.js
> Bug Fixes for Settings and Landing page

- client/src/components/WorkoutsView/MyWorkouts.js
- client/src/components/WorkoutsView/WorkoutModule/AddWorkout.js
Added styling to placeholder, limited text characters to exercise names & limited exercises to 10 per workout.
> Workouts bug fixes

- client/src/components/ProgressView/ProgressDayView.js
- client/src/components/ProgressView/ProgressGraph/Details.js
- client/src/components/ProgressView/index.js
- client/src/components/SettingsView/MainSettings.js
- client/src/components/SettingsView/SettingsView.js
Fixed progress and setting page view errors
> Fixed progress and setting page view errors

- client/src/components/ProgressView/ProgressGraph/Graph.js
- client/src/components/SettingsView/MainSettings.js
- client/src/components/SettingsView/SettingsView.js
- client/src/index.css
> Progress graph premium button

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/components/WorkoutsView/MyWorkouts.js
Co-authored-by: Matthew Wright <matthewbwright@gmail.com>
Added React Suspense & Lazy to every component that loads in App.js for performance boost. 
Fixes # (issue) - none
Renders correctly to the screen. 
Functionality remains after implementing Suspense & Lazy.
> Added React Suspense & Lazy Loading to every component

- client/src/components/ScheduleView/Calendar.js
- client/src/components/ScheduleView/ScheduleWorkout.js
- client/src/components/ScheduleView/index.js
Functionality to push to workouts page when no workouts scheduled
> Functionality to push to workouts page when no workouts scheduled

- client/README.md
> Read me update

- client/src/components/ForgotPassword.js
- client/src/components/Login.js
- client/src/components/ProgressView/MetricModule/EditMetric.js
- client/src/components/WorkoutsView/MyWorkouts.js
- client/src/index.js
Edit workout on filtered category + Password reset
> Edit workout on filtered category + Password reset
